[build]
  command = "npm run build"
  publish = "dist"

# Ye part add karein taaki public folder ki files copy ho jayein
[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
